# FROM openjdk:21-jdk-slim
# WORKDIR /app
# COPY pom.xml .
# COPY mvnw .
# COPY .mvn .mvn
# RUN chmod +x mvnw
# RUN ./mvnw dependency:go-offline
# COPY src ./src
# EXPOSE 9090
# CMD ["./mvnw", "spring-boot:run"]

FROM openjdk:21-jdk-slim
WORKDIR /app

# Copiar archivos necesarios para Maven
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn
RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline

COPY src ./src

EXPOSE 9090 5005

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]