spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "https://"
                allowedMethods:
                  - GET
                  - PUT
                  - DELETE
                  - PATCH
                  - POST
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: health , gateway , info