name: Build and deploy container app to Azure Web App - msvc-gateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55

      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-gateway:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@1384c340ab2dda50fed2bee3041d1d87018aa5e8
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_421A39DDBC904D2FA54352B7652625A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_543DC9DC3CF14A71AEB9A91D9BEA1CC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CAD828C3100249F180F86238C788262A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@3f1742a3b209ebd19d82b914f43fe1d6b919e536
        with:
          app-name: "msvc-gateway"
          slot-name: "Production"
          images: "${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-gateway:latest"
